name: Deploy to AWS S3

on:
  push:
    branches:
      - develop

jobs:
  deploy-develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    if: endsWith(github.ref, 'develop')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install and Build
        run: |
          yarn
          yarn g:build

      - name: Append Environment Variables to .env
        run: |
          cat <<EOF >> apps/web/.env
          # These API keys are intentionally public. Please do not report them - thank you for your concern.
          REACT_APP_AMPLITUDE_PROXY_URL="https://interface.gateway.uniswap.org/v1/amplitude-proxy"
          REACT_APP_AWS_API_ENDPOINT="https://interface-graphql.kittycorn.io/v1/graphql"
          REACT_APP_AWS_REALTIME_ENDPOINT="wss://beta.realtime.gateway.uniswap.org/graphql"
          REACT_APP_AWS_REALTIME_TOKEN="realtime-3DDE0DA0-3408-4FD0-9DC3-5E285D70D29C"
          REACT_APP_INFURA_KEY="4bf032f2d38a4ed6bb975b80d6340847"
          REACT_APP_QUICKNODE_ENDPOINT_NAME=""
          REACT_APP_QUICKNODE_ENDPOINT_TOKEN=""
          REACT_APP_QUICKNODE_MONAD_TESTNET_RPC_URL=""
          REACT_APP_MOONPAY_API=""
          REACT_APP_MOONPAY_LINK=""
          REACT_APP_MOONPAY_PUBLISHABLE_KEY=""
          REACT_APP_SENTRY_DSN=""
          REACT_APP_STATSIG_PROXY_URL="${{ secrets.REACT_APP_STATSIG_API_KEY }}"
          REACT_APP_TEMP_API_URL=""
          REACT_APP_UNISWAP_BASE_API_URL="https://interface.gateway.uniswap.org"
          REACT_APP_UNISWAP_GATEWAY_DNS="https://interface.gateway.uniswap.org/v2"
          REACT_APP_WALLET_CONNECT_PROJECT_ID="c6c9bacd35afa3eb9e6cccf6d8464395"
          REACT_APP_IS_UNISWAP_INTERFACE=true
          REACT_APP_STATSIG_API_KEY="client-zdC7XY3i3v1wVBEXMOcfZPebmVD7oxp9993jDLuPX3X"
          REACT_APP_STAGING=true
          EOF

      - name: Deploy Develop to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --cache-control no-store
        env:
          AWS_S3_BUCKET: develop-web.kittycorn.io
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
          SOURCE_DIR: 'build'